View-Pharm/YakAl

backend-server/build.gradle
backend-server/src/main/java/com/viewpharm/yakal/controller/DoseController.java
backend-server/src/main/java/com/viewpharm/yakal/domain/Dose.java
backend-server/src/main/java/com/viewpharm/yakal/domain/Notification.java
backend-server/src/main/java/com/viewpharm/yakal/domain/Prescription.java
backend-server/src/main/java/com/viewpharm/yakal/domain/User.java
backend-server/src/main/java/com/viewpharm/yakal/dto/DoesRequestDto.java
backend-server/src/main/java/com/viewpharm/yakal/dto/DoseDto.java
backend-server/src/main/java/com/viewpharm/yakal/dto/PercentDto.java
backend-server/src/main/java/com/viewpharm/yakal/exception/ErrorCode.java
backend-server/src/main/java/com/viewpharm/yakal/repository/DoseRepository.java
backend-server/src/main/java/com/viewpharm/yakal/repository/PrescriptionRepository.java
backend-server/src/main/java/com/viewpharm/yakal/service/DoseService.java

1. Create 스케쥴
2. Read 스케쥴 하루단위, Percent (1일,1주,한달)
3. Update 약개수, 복용 여부
4. Delete 스케쥴 삭제
ps) 중복 API 생각중..  아무 리뷰 대환영

✨Dose Api 대부분 작성

---

backend-server/src/main/java/com/viewpharm/yakal/controller/AuthController.java
backend-server/src/main/java/com/viewpharm/yakal/security/JwtProvider.java
backend-server/src/main/java/com/viewpharm/yakal/service/AuthService.java
backend-server/src/main/java/com/viewpharm/yakal/utils/OAuth2Util.java

- 카카오 로그인 구현된 것 테스트 완료했습니다.
- 구글 로그인 기본 폼 기반으로 작성하여 구현했습니다.
- 그 후 테스트 진행 까지 완료 했습니다.

✨  Kakao Login 테스트 및 Google Login 구현/테스트 완료

---

backend-server/.gitignore
backend-server/src/main/java/com/viewpharm/yakal/YakalApplication.java
backend-server/src/main/java/com/viewpharm/yakal/service/NotificationScheduleService.java

필요없는 로그, 출력 코드 삭제했습니다.
스케줄링 코드 임시 주석 처리 했습니다

🔥 필요없는 코드 삭제, 스케줄링 임시 주석 처리

---

frontend-android/app/src/main/AndroidManifest.xml
frontend-android/app/src/main/java/com/viewpharm/yakal/adapter/PillAdapter.kt
frontend-android/app/src/main/java/com/viewpharm/yakal/adapter/PillTodoAdapter.kt
frontend-android/app/src/main/java/com/viewpharm/yakal/ui/HomeMainFragment.kt
frontend-android/app/src/main/java/com/viewpharm/yakal/ui/OverlapBottomDialog.kt
frontend-android/app/src/main/java/com/viewpharm/yakal/view/CalenderActivity.kt
frontend-android/app/src/main/java/com/viewpharm/yakal/view/MainActivity.kt
frontend-android/app/src/main/res/drawable/ic_custom_big_close.xml
frontend-android/app/src/main/res/layout/activity_main.xml
frontend-android/app/src/main/res/layout/fragment_overlap_bottom_sheet.xml
frontend-android/app/src/main/res/layout/item_home_pill_sub.xml

🐛 fix: Dialog 연결 오류 해결

---

backend-server/.gitmodules
backend-server/Dockerfile
backend-server/build.gradle

- SubModule 추가
- buile.gradle 수정
- Docker File 추가

✨ feat: CI/CD 세팅

---

.gitmodules

🐛 submodule 인식 불가 해결

---

backend-server/src/main/java/com/viewpharm/yakal/controller/AuthController.java
backend-server/src/main/java/com/viewpharm/yakal/service/AuthService.java
backend-server/src/main/java/com/viewpharm/yakal/utils/OAuth2Util.java

orElse는 null이든 아니든 무조건 해당 값을 넣으므로, 로그인 시 중복 문제가 일어났음
로그인 시 편하게 AccessToken을 받기 위해 추가함 목록은 아래와 같음
후에 login시 소셜로그인 후 받은 토큰을 바로 /auth/[provider]으로 post 보내면 됨.
- /kakao/callback
- /google/callback
- /apple/callback

🐛 ✨ deploy: Login Error 수정, Dev용 EndPoint 추가, yml 수정

---

backend-server/src/main/java/com/viewpharm/yakal/controller/ImageController.java
backend-server/src/main/java/com/viewpharm/yakal/domain/Image.java
backend-server/src/main/java/com/viewpharm/yakal/domain/Medical.java
backend-server/src/main/java/com/viewpharm/yakal/domain/MobileUser.java
backend-server/src/main/java/com/viewpharm/yakal/exception/ErrorCode.java
backend-server/src/main/java/com/viewpharm/yakal/repository/ImageRepository.java
backend-server/src/main/java/com/viewpharm/yakal/repository/MedicalRepository.java
backend-server/src/main/java/com/viewpharm/yakal/service/AuthService.java
backend-server/src/main/java/com/viewpharm/yakal/service/ImageService.java
backend-server/src/main/java/com/viewpharm/yakal/type/EImageUseType.java

✨Feat: Image Upload & Download

---

backend-server/src/main/java/com/viewpharm/yakal/dto/request/CreateScheduleDto.java
backend-server/src/main/java/com/viewpharm/yakal/dto/request/OneMedicineScheduleDto.java
backend-server/src/main/java/com/viewpharm/yakal/dto/request/OneScheduleDto.java

약추가 API 안되서 긴급 PullRequest 올립니다.

🐛fix : 약추가 API DTO 수정

---

backend-server/src/main/java/com/viewpharm/yakal/controller/UserController.java
backend-server/src/main/java/com/viewpharm/yakal/domain/User.java
backend-server/src/main/java/com/viewpharm/yakal/dto/request/IdentifyDto.java
backend-server/src/main/java/com/viewpharm/yakal/dto/response/UserInfoDto.java
backend-server/src/main/java/com/viewpharm/yakal/exception/ErrorCode.java
backend-server/src/main/java/com/viewpharm/yakal/service/UserService.java
backend-server/src/main/java/com/viewpharm/yakal/utils/OAuth2Util.java
frontend-web/index.html
frontend-web/src/expert/api/user.ts
frontend-web/src/expert/layout/main/index.tsx
frontend-web/src/expert/page/login/identification-page/index.tsx
frontend-web/src/expert/page/login/identification-success/index.tsx
frontend-web/src/expert/page/login/identification-success/style.ts
frontend-web/src/expert/page/login/login-main/style.ts
frontend-web/src/expert/page/main/dashboard/index.tsx
frontend-web/src/expert/store/store.ts
frontend-web/src/global/router.tsx
frontend-web/src/main.tsx

1. 전문가 웹 본인인증 연동
2. 서버 본인인증 API 구현

✨ feat: 전문가 웹 본인인증 연동, 서버 본인인증 API 구현

---

frontend-ios/YakAl/YakAl.xcodeproj/project.pbxproj
frontend-ios/YakAl/YakAl/Resources/Assets.xcassets/icon/Check_fill.imageset/Check_fill.svg
frontend-ios/YakAl/YakAl/Resources/Assets.xcassets/icon/Check_fill.imageset/Contents.json
frontend-ios/YakAl/YakAl/Resources/StoryBoards/TabRouter.storyboard
frontend-ios/YakAl/YakAl/Sources/Views/Common/BlueHorizontalButton.swift
frontend-ios/YakAl/YakAl/Sources/Views/Mypage/AlertSettingSwiftUIView.swift
frontend-ios/YakAl/YakAl/Sources/Views/Mypage/ConfromityTestSwiftUIView.swift
frontend-ios/YakAl/YakAl/Sources/Views/Mypage/DepressionTestSwiftUIView.swift
frontend-ios/YakAl/YakAl/Sources/Views/Mypage/DiagnosticTestSwiftUIView.swift
frontend-ios/YakAl/YakAl/Sources/Views/Mypage/DrinkingTestSwiftUIView.swift
frontend-ios/YakAl/YakAl/Sources/Views/Mypage/HealthFoodSwiftUIView.swift
frontend-ios/YakAl/YakAl/Sources/Views/Mypage/InfoBoxView.swift
frontend-ios/YakAl/YakAl/Sources/Views/Mypage/InsomniaTestSwiftUIView.swift
frontend-ios/YakAl/YakAl/Sources/Views/Mypage/KakaoSettingView.swift
frontend-ios/YakAl/YakAl/Sources/Views/Mypage/MypageSwiftUIView.swift
frontend-ios/YakAl/YakAl/Sources/Views/Mypage/OptionButton.swift
frontend-ios/YakAl/YakAl/Sources/Views/Mypage/ResultBoxSwiftUIView.swift
frontend-ios/YakAl/YakAl/Sources/Views/Mypage/RowQuetionView.swift
frontend-ios/YakAl/YakAl/Sources/Views/Mypage/SettingButtonSwiftUI.swift
frontend-ios/YakAl/YakAl/Sources/Views/Mypage/SettingSwiftUIView.swift
frontend-ios/YakAl/YakAl/Sources/Views/Mypage/SmokingTestSwiftUIView.swift
frontend-ios/YakAl/YakAl/Sources/Views/Mypage/TestDoneSwiftUIView.swift
frontend-ios/YakAl/YakAl/Sources/Views/Mypage/TestListSwiftUIView.swift
frontend-ios/YakAl/YakAl/Sources/Views/Mypage/TimeSettingView.swift
frontend-ios/YakAl/YakAl/Sources/Views/Mypage/WishYakalSwiftUIView.swift

우울증, 복약 순응도 테스트 페이지 완료 했습니다.
그외 네비게이션 연결하였고, 헤더 설정은 진행중에 있습니다.

✨ feat : 설문조사 페이지 : 우울증, 복약 순응도

---

frontend-android/app/src/main/java/com/viewpharm/yakal/main/activity/MainActivity.kt
frontend-android/app/src/main/java/com/viewpharm/yakal/main/fragment/MainProfileFragment.kt
frontend-android/app/src/main/java/com/viewpharm/yakal/main/fragment/NotificationSettingFragment.kt
frontend-android/app/src/main/java/com/viewpharm/yakal/main/fragment/OpinionExitFragment.kt
frontend-android/app/src/main/java/com/viewpharm/yakal/main/fragment/OpinionFragment.kt
frontend-android/app/src/main/java/com/viewpharm/yakal/main/model/Opinion.kt
frontend-android/app/src/main/java/com/viewpharm/yakal/main/viewmodel/NotificationSettingViewModel.kt
frontend-android/app/src/main/java/com/viewpharm/yakal/main/viewmodel/OpinionViewModel.kt
frontend-android/app/src/main/java/com/viewpharm/yakal/view/SplashActivity.kt
frontend-android/app/src/main/res/drawable/btn_opinion_exit.xml
frontend-android/app/src/main/res/drawable/switch_thumb.xml
frontend-android/app/src/main/res/drawable/switch_track.xml
frontend-android/app/src/main/res/drawable/switch_track_off.xml
frontend-android/app/src/main/res/drawable/switch_track_on.xml
frontend-android/app/src/main/res/layout/fragment_main_profile.xml
frontend-android/app/src/main/res/layout/fragment_notification_setting.xml
frontend-android/app/src/main/res/layout/fragment_opinion.xml
frontend-android/app/src/main/res/layout/fragment_opinion_exit.xml
frontend-android/app/src/main/res/navigation/main_nav_graph.xml

설문조사 제외
앱 설정, 알림 설정, 약알에게 바라는 점 완료 했습니다.

✨ feat: mypage 설문조사 제외 완료

---

backend-server/src/main/java/com/viewpharm/yakal/controller/AdminController.java
backend-server/src/main/java/com/viewpharm/yakal/controller/DoseController.java
backend-server/src/main/java/com/viewpharm/yakal/dto/response/OneDaySummaryDto.java
backend-server/src/main/java/com/viewpharm/yakal/repository/UserRepository.java
backend-server/src/main/java/com/viewpharm/yakal/service/DoseService.java
backend-server/src/main/java/com/viewpharm/yakal/service/UserService.java

fix : 자잘한 수정

---

ocr/ocr.py

Feat : OCR 추가

---

backend-server/src/main/java/com/viewpharm/yakal/domain/Guardian.java
backend-server/src/main/java/com/viewpharm/yakal/domain/User.java
backend-server/src/main/java/com/viewpharm/yakal/exception/ErrorCode.java
backend-server/src/main/java/com/viewpharm/yakal/repository/GuardianRepository.java
backend-server/src/main/java/com/viewpharm/yakal/service/GuardianService.java

일대다 관계로 변경했습니다.
보호자나 환자 가져올 때 최근에 추가된 한명만 가져오도록 했습니다

⚡ 보호자와 환자 서로 여러명 가능하도록 변경

---

frontend-hybrid/yakal/assets/icons/circle_1.svg
frontend-hybrid/yakal/assets/icons/circle_2.svg
frontend-hybrid/yakal/assets/icons/circle_3.svg
frontend-hybrid/yakal/assets/icons/circle_4.svg
frontend-hybrid/yakal/assets/icons/circle_5.svg
frontend-hybrid/yakal/assets/icons/circle_6.svg
frontend-hybrid/yakal/lib/main.dart
frontend-hybrid/yakal/lib/screens/Profile/profile_screen.dart
frontend-hybrid/yakal/lib/screens/Survey/SurveyDetail/survey_detail_bokyak_screen.dart
frontend-hybrid/yakal/lib/screens/Survey/survery_senior_screen.dart
frontend-hybrid/yakal/lib/widgets/Profile/profile_test_button_widget.dart

✨ Feat : Test Start 

---

frontend-hybrid/yakal/assets/icons/Check_active.svg
frontend-hybrid/yakal/assets/icons/Check_disable.svg
frontend-hybrid/yakal/lib/main.dart
frontend-hybrid/yakal/lib/models/Survey/question_model.dart
frontend-hybrid/yakal/lib/models/Survey/survey_model.dart
frontend-hybrid/yakal/lib/models/Survey/survey_result_model.dart
frontend-hybrid/yakal/lib/screens/Survey/SurveyDetail/survey_detail_bokyak_screen.dart
frontend-hybrid/yakal/lib/screens/Survey/survery_senior_screen.dart
frontend-hybrid/yakal/lib/screens/Survey/survey_result_screen.dart
frontend-hybrid/yakal/lib/viewModels/Survey/survey_detail_bokyak_controller.dart
frontend-hybrid/yakal/lib/widgets/Survey/survey_header_widget.dart

MVVM
Survey Model
-> 
Survey ViewModel -> View구현 완려했습니다.

♻️ Suryvey MVVM 적용 

---

frontend-hybrid/yakal/ios/Podfile.lock
frontend-hybrid/yakal/lib/screens/Medication/ocrEnvelop/EnvelopOcrEntry/screen.dart

iPhone 15, plus, pro, pro max 테스트 완료

🐛  약 봉투 OCR 진입 페이지 이미지 오버플로우

---

backend-server/src/main/java/com/viewpharm/yakal/domain/Risk.java
backend-server/src/main/java/com/viewpharm/yakal/type/EMedicalProperties.java

beers_criteria가 항콜린성이랑 겹쳐지는경우는 없는것 같아서 컬럼을 합쳤습니다.

refactor : beers_criteria enum화

---

backend-server/src/main/java/com/viewpharm/yakal/dto/response/OneTimeScheduleDto.java
backend-server/src/main/java/com/viewpharm/yakal/service/DoseService.java

기존의 약 조회 api에서 실제약물이름까지 반환하는것을 추가하였습니다.

feat : 약조회 api 에서 약이름 추가

---

backend-server/src/main/java/com/viewpharm/yakal/controller/PrescriptionController.java
backend-server/src/main/java/com/viewpharm/yakal/dto/response/PrescriptionDto.java
backend-server/src/main/java/com/viewpharm/yakal/service/PrescriptionService.java

fix : 처방전 조회 api 수정

---

frontend-hybrid/yakal/lib/main.dart
frontend-hybrid/yakal/lib/screens/Detail/screen.dart
frontend-hybrid/yakal/lib/screens/Profile/Info/info_boho_screen.dart
frontend-hybrid/yakal/lib/utilities/api/api.dart
frontend-hybrid/yakal/lib/widgets/Base/custom_expansion_tile.dart
frontend-hybrid/yakal/lib/widgets/Home/home_info_layout.dart
frontend-hybrid/yakal/lib/widgets/Home/pill_todo_parent_item.dart
frontend-hybrid/yakal/pubspec.lock
frontend-hybrid/yakal/pubspec.yaml
frontend-hybrid/yakal/test/widget_test.dart

1. 메인 화면 figma디자인에 맞게 스타일 변경했습니다.
2. 접속시 accesToken여부에 따라 initial Route다르게 했습니다.
``` dart
const storage = FlutterSecureStorage();
final accessToken = await storage.read(key: 'ACCESS_TOKEN');
// Fix to portrait mode
await SystemChrome.setPreferredOrientations([
DeviceOrientation.portraitUp,
DeviceOrientation.portraitDown,
]);
// locator init
initializeDateFormatting().then((value) =>
runApp(MyApp(initialRoute: accessToken != null ? '/' : '/login')));
```

💄 style : 메인 화면 스타일 적용

---

backend-server/build.gradle
backend-server/src/main/java/com/viewpharm/yakal/domain/User.java
backend-server/src/main/java/com/viewpharm/yakal/service/UserService.java
backend-server/src/main/resources/schema.sql

유저 최초 로그인시 아침, 점심, 저녁 디폴트 값 추가했습니다

⚡  유저 최초 로그인시 아침, 점심, 저녁 디폴트 값 추가

---

frontend-hybrid/yakal/lib/models/Home/home_info_model.dart
frontend-hybrid/yakal/lib/models/Home/pill_todo_children.dart
frontend-hybrid/yakal/lib/provider/Home/pill_todo_provider.dart
frontend-hybrid/yakal/lib/repository/Home/pill_todo_repository.dart
frontend-hybrid/yakal/lib/screens/Home/home_screen.dart
frontend-hybrid/yakal/lib/utilities/api/api.dart
frontend-hybrid/yakal/lib/viewModels/Home/home_view_model.dart
frontend-hybrid/yakal/lib/widgets/Home/pill_todo_chidren_item.dart
frontend-hybrid/yakal/lib/widgets/Home/pill_todo_layout.dart
frontend-hybrid/yakal/lib/widgets/Home/pill_todo_parent_item.dart

홈 스크린
- 하루 복용 목록 서버 연동
- Kims Data 연동
- 체크박스 Click시 서버 연동
완료 했습니다.

✨ Feat: 홈 스크린 연동 완료

---

backend-server/src/main/java/com/viewpharm/yakal/controller/DoseController.java
backend-server/src/main/java/com/viewpharm/yakal/repository/DoesNameRepository.java
backend-server/src/main/java/com/viewpharm/yakal/service/DoseService.java

Query로 limit 1을 이용하여 하나만 가져오게 했습니다.

fix : 약이름으로 코드 가져오는 api (중복된 약이름 경우를 위해) 수정

---

frontend-hybrid/yakal/ios/GoogleService-Info.plist
frontend-hybrid/yakal/ios/Runner.xcodeproj/project.pbxproj
frontend-hybrid/yakal/ios/Runner/AppDelegate.swift

feat: APNS, FCM 파일 적용 (iOS)

---

backend-server/src/main/java/com/viewpharm/yakal/controller/DoseController.java
backend-server/src/main/java/com/viewpharm/yakal/dto/request/OneMedicineScheduleDto.java
backend-server/src/main/java/com/viewpharm/yakal/repository/DoseNameRepository.java
backend-server/src/main/java/com/viewpharm/yakal/service/DoseService.java

KDcode 와 ATCcode가 없을떄도 추가할 수 있게끔 수정했습니다.

✨feat : KDcode 와 ATCcode가 없는 경우 사용자가 입력한 이름을 기반으로 가장 유사한 약으로 추가

---

backend-server/src/main/java/com/viewpharm/yakal/controller/UserController.java
backend-server/src/main/java/com/viewpharm/yakal/domain/User.java
backend-server/src/main/java/com/viewpharm/yakal/dto/request/UserDeviceRequestDto.java
backend-server/src/main/java/com/viewpharm/yakal/service/NotificationScheduleService.java
backend-server/src/main/java/com/viewpharm/yakal/service/UserService.java

✨ 디바이스 토큰 등록

---

frontend-hybrid/yakal/android/app/build.gradle
frontend-hybrid/yakal/ios/GoogleService-Info.plist
frontend-hybrid/yakal/ios/Runner.xcodeproj/project.pbxproj
frontend-hybrid/yakal/ios/Runner/Info.plist
frontend-hybrid/yakal/ios/Runner/RunnerRelease.entitlements
frontend-hybrid/yakal/lib/main.dart
frontend-hybrid/yakal/lib/screens/Survey/survery_senior_screen.dart
frontend-hybrid/yakal/lib/widgets/Home/pill_todo_chidren_item.dart

✨feat : xcode setting

---

frontend-hybrid/yakal/lib/main.dart
frontend-hybrid/yakal/lib/models/Profile/special_note_model.dart
frontend-hybrid/yakal/lib/screens/Profile/Info/info_star_screen.dart
frontend-hybrid/yakal/lib/screens/Survey/survey_result_screen.dart
frontend-hybrid/yakal/lib/viewModels/Profile/special_list_view_model.dart

1. 완료된 결과 다시하러가기 버튼
2. 특이사항 통신 
3. 날짜

✨ Feat: 특이사항, 다시하러가기, 날짜

---

frontend-hybrid/yakal/lib/models/Profile/user.dart
frontend-hybrid/yakal/lib/screens/Login/LoginProcess/LoginFinished/screen.dart
frontend-hybrid/yakal/lib/screens/Profile/Info/info_hospital_screen.dart
frontend-hybrid/yakal/lib/screens/Profile/Info/info_star_screen.dart
frontend-hybrid/yakal/lib/screens/Profile/profile_screen.dart
frontend-hybrid/yakal/lib/screens/Setting/setting_screen.dart
frontend-hybrid/yakal/lib/viewModels/Profile/special_list_view_model.dart
frontend-hybrid/yakal/lib/viewModels/Profile/user_view_model.dart
frontend-hybrid/yakal/lib/widgets/Profile/profile_setting_row_box_widget.dart
frontend-hybrid/yakal/pubspec.lock
frontend-hybrid/yakal/pubspec.yaml

입원 기록 / 응급실 방문 기록 통신 연결완료 후 자잘한 디자인작업 들어갔습니다.

✨feat: 입원 기록 / 응급실 방문 기록 통신 연결, 자잘한 디자인작업

---

backend-server/src/main/java/com/viewpharm/yakal/base/utils/ImageUtil.java
backend-server/src/main/java/com/viewpharm/yakal/prescription/dto/response/DoseAntiAllDto.java
backend-server/src/main/java/com/viewpharm/yakal/prescription/dto/response/DoseAntiDto.java
backend-server/src/main/java/com/viewpharm/yakal/prescription/repository/DoseRepository.java
backend-server/src/main/java/com/viewpharm/yakal/prescription/service/DoseService.java
backend-server/src/main/java/com/viewpharm/yakal/user/controller/ExpertController.java
ocr/ocr.py

항콜린성 약물 가져올시 위험도 추가, ocr 주석 추가

✨ 항콜린성 약물 가져올시 위험도 추가, ocr 주석 추가

---

frontend-hybrid/yakal/lib/main.dart
frontend-hybrid/yakal/lib/screens/Home/home_screen.dart
frontend-hybrid/yakal/lib/screens/Survey/SurveyDetail/survey_detail_screen.dart
frontend-hybrid/yakal/lib/screens/Survey/survery_senior_screen.dart
frontend-hybrid/yakal/lib/screens/Survey/survey_normal_screen.dart
frontend-hybrid/yakal/lib/screens/Survey/survey_result_screen.dart
frontend-hybrid/yakal/lib/viewModels/Survey/survey_detail_bokyak_controller.dart
frontend-hybrid/yakal/lib/widgets/Profile/profile_setting_row_box_widget.dart
frontend-hybrid/yakal/lib/widgets/Setting/setting_time_selection_widget.dart

- 범위 시간 설정
- 테스트 목록 개선
- 홈 화면 불투명 박스 삭제
- 스낵바 시간 연장

✨Feat: 범위 시간 설정/테스트 목록 개선 

---

backend-server/src/main/java/com/viewpharm/yakal/medicalappointment/service/MedicalAppointmentService.java
backend-server/src/main/java/com/viewpharm/yakal/medicalestablishment/repository/ExpertCertificationRepository.java
backend-server/src/main/java/com/viewpharm/yakal/prescription/repository/DoseRepository.java
backend-server/src/main/java/com/viewpharm/yakal/survey/service/SurveyService.java
backend-server/src/main/java/com/viewpharm/yakal/user/controller/ExpertController.java

[전문가 테스트 및 수정](https://github.com/View-Pharm/YakAl/commit/490672d138f1866c87c66070a5a55e000459f98c)

⚡ 전문가 테스트 및 수정

---

backend-server/src/main/java/com/viewpharm/yakal/prescription/repository/DoseRepository.java

약 이름 가져오기 변경

---

backend-server/src/main/java/com/viewpharm/yakal/desire/controller/DesireController.java
backend-server/src/main/java/com/viewpharm/yakal/desire/domain/Desire.java
backend-server/src/main/java/com/viewpharm/yakal/desire/dto/request/DesireRequestDto.java
backend-server/src/main/java/com/viewpharm/yakal/desire/dto/response/DesireAllDto.java
backend-server/src/main/java/com/viewpharm/yakal/desire/dto/response/DesireListDto.java
backend-server/src/main/java/com/viewpharm/yakal/desire/repository/DesireRepository.java
backend-server/src/main/java/com/viewpharm/yakal/desire/service/DesireService.java
backend-server/src/main/java/com/viewpharm/yakal/user/controller/AdminController.java
backend-server/src/main/java/com/viewpharm/yakal/user/domain/User.java

✨  바라는 점 추가
